### PR TITLE
Update 2020-06-24-css-translate-values-in-javascript.md

### PR DESCRIPTION
**Pull request by lumenier1**
Fix bug if matrix is 'undefined'

### CODE REVIEW

**Comment by zellwk** [comment]
Can I ask when will matrix be undefined?

**Comment by lumenier1** [comment]
I didn't debug it deeply but if you generate multiple DOM elements dynamically with css keyframe animation you probably might catch this bug. So, in my case I passed dynamic elements to 'getTranslateValues' function and got an exception of undefined matrix.
I'll try to find some time to make more reliable research of this bug.

**Comment by zellwk** [comment]
@lumenier1 That's cool to know! Just wondering how you generate elements dynamically with CSS Keyframe animation? I never heard of something like this before, so would love to have a code example if possible.

**Comment by lumenier1** [comment]
You can simply create dynamic elements with particular class: https://codepen.io/testcoder1/pen/BaQPxRJ

**Comment by zellwk** [comment]
Perfect. Thank you.

**Pull request merged**
