### PR TITLE
Editing

### PR DESCRIPTION
**Pull request by mtkramer**
I made some grammatical corrections, clarifications, and made emoji punctuation consistent.  I could follow your train of thought through most of this article but you must type very fast as I had to read it fast to so.  The clarifications were to help others with parts that might be confusing to slower readers or people who didn't get which idioms your were trying to express.  I also just wanted to read it again. ;)

I really enjoyed this article and I believe I understand the event loop much better now.  Thanks!

### CODE REVIEW

**Comment by zellwk** [comment]
Sorry for the super late reply. I keep wanting to try and merge this PR, but I haven't found the space to do so. There are too many different kinds of changes in there :/

**Comment by zellwk** [comment]
No worries, @mtkramer. Here's what you can do: Please separate change in writing style vs typo corrections into different PRs. This will help me merge typos comments directly. 

For style changes, I can review them separately.

**Comment by mtkramer** [comment]
I can do that.  I'll start working on it later today.

**Comment by mtkramer** [comment]
Closing this PR as a new one was submitted.

**Pull request closed without merging**
